{ config, pkgs, lib, ... }:
let
  # All config files live in this repo. mkOutOfStoreSymlink points a
  # home.file symlink back at the working tree, so edits take effect
  # immediately with no `home-manager switch` — the declarative
  # successor to the GNU Stow symlinks this repo used to rely on.
  dotfiles = "${config.home.homeDirectory}/.dotfiles";
  liveLink = path: config.lib.file.mkOutOfStoreSymlink "${dotfiles}/${path}";
in {
  home.username = "will";
  home.homeDirectory = "/home/will";

  home.stateVersion = "25.05";

  # GNOME settings (generated by gnome-settings-export via dconf2nix —
  # don't hand-edit; tweak in the GUI then re-run the export script).
  imports = [
    ./modules/gnome/terminal.nix
    ./modules/gnome/desktop.nix
    ./modules/gnome/extensions.nix
  ];

  # Packages. Configs that belong to a package are wired up declaratively
  # below (programs.git) or via home.file; nothing is stowed anymore.
  home.packages = with pkgs; [
    gh
    neovim
    tmux
    btop
    tree
    lazygit
    lazydocker

    # Rust-built CLI tools (formerly `cargo install`; rustup itself stays
    # in install.sh for actual Rust development)
    bat
    du-dust
    fd
    ripgrep
    ripgrep-all
    procs

    # Formerly a curl-pipe-sh installer in install.sh
    uv

    # Terminal emulator — config in config/wezterm/.wezterm.lua
    wezterm

    # Node.js LTS (formerly NodeSource apt repo)
    nodejs

    # Terminal font
    (iosevka-bin.override { variant = "SGr-IosevkaTermSS18"; })

    # GUI apps (formerly flatpak/snap). Ubuntu 24.04 blocks the
    # unprivileged user namespaces their sandboxes need — install.sh
    # ships AppArmor profiles (apparmor/) granting userns per app.
    obsidian
    slack
    vscode
  ];

  # Dotfiles formerly symlinked by GNU Stow, now owned by home-manager.
  # Frequently-edited configs use liveLink (mkOutOfStoreSymlink) so repo
  # edits are live; the static helper script is copied into the store.
  home.file = {
    ".wezterm.lua".source = liveLink "config/wezterm/.wezterm.lua";
    ".tmux.conf".source = liveLink "config/tmux/.tmux.conf";
    # Only settings.json is dotfiles-managed; the rest of ~/.claude is
    # runtime state and secrets (gitignored). liveLink keeps it writable.
    ".claude/settings.json".source = liveLink "config/claude/settings.json";
    ".local/bin/gnome-settings-export" = {
      source = ./bin/gnome-settings-export;
      executable = true;
    };
    ".local/bin/update-config" = {
      source = ./bin/update-config.sh;
      executable = true;
    };
  };

  # Make fontconfig see fonts from home.packages on non-NixOS.
  fonts.fontconfig.enable = true;

  # Non-NixOS (Ubuntu) integration: adds ~/.nix-profile/share to
  # XDG_DATA_DIRS (via environment.d) so GNOME finds desktop entries
  # and icons of nix-installed GUI apps (e.g. zen-beta).
  targets.genericLinux.enable = true;

  # Git — formerly the stowed ~/.gitconfig. programs.git also provides the
  # git package, so `git` is not duplicated in home.packages above.
  programs.git = {
    enable = true;
    userName = "Will C. Forte";
    userEmail = "willcforte@gmail.com";
    extraConfig = {
      push.autoSetupRemote = true;
      # Clear any inherited helper (empty string), then delegate to gh.
      credential."https://github.com".helper = [ "" "!gh auth git-credential" ];
      credential."https://gist.github.com".helper = [ "" "!gh auth git-credential" ];
    };
  };

  # home-manager owns ~/.bashrc and ~/.profile (first switch on a machine
  # needs `switch -b backup` to move the pre-existing real files aside).
  # Machine-specific lines and secrets go in ~/.bashrc.local — never here.
  programs.bash = {
    enable = true;
    # Match Ubuntu's stock history behavior.
    historyControl = [ "ignoreboth" ];
    historySize = 1000;
    historyFileSize = 2000;
    shellAliases = {
      ccode = "claude";
      ls = "ls --color=auto";
      grep = "grep --color=auto";
      ll = "ls -alF";
      la = "ls -A";
      l = "ls -CF";
    };
    initExtra = ''
      # bash-completion (Ubuntu system package)
      if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
        fi
      fi

      export PATH="$HOME/.local/bin:$PATH"

      # Rust toolchain (rustup is installed by install.sh)
      [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

      # Nix daemon env for non-login shells
      [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ] \
        && . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

      # Machine-specific config and secrets (not in dotfiles repo)
      [ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
    '';
  };

  # Shell integrations — these enable the packages AND wire up their
  # bash init hooks declaratively.
  programs.starship.enable = true;
  programs.zoxide.enable = true;

  programs.home-manager.enable = true;
}
