{ pkgs, ... }: {
  home.username = "will";
  home.homeDirectory = "/home/will";

  home.stateVersion = "25.05";

  # GNOME settings (generated by gnome-settings-export via dconf2nix —
  # don't hand-edit; tweak in the GUI then re-run the export script).
  imports = [
    ./gnome/terminal.nix
    ./gnome/desktop.nix
    ./gnome/extensions.nix
  ];

  # Packages only — their configs are stowed (stow/git/.gitconfig,
  # stow/tmux/.tmux.conf) and take precedence over anything
  # home-manager would generate. Keep config out of here.
  home.packages = with pkgs; [
    git
    gh
    neovim
    tmux
    btop
    tree
    lazygit
    lazydocker

    # Rust-built CLI tools (formerly `cargo install`; rustup itself stays
    # in install.sh for actual Rust development)
    bat
    du-dust
    fd
    ripgrep
    ripgrep-all
    procs

    # Formerly a curl-pipe-sh installer in install.sh
    uv

    # Terminal emulator — config is stowed (.wezterm.lua)
    wezterm

    # Node.js LTS (formerly NodeSource apt repo)
    nodejs

    # Terminal font
    (iosevka-bin.override { variant = "SGr-IosevkaTermSS18"; })
  ];

  # Make fontconfig see fonts from home.packages on non-NixOS.
  fonts.fontconfig.enable = true;

  # Non-NixOS (Ubuntu) integration: adds ~/.nix-profile/share to
  # XDG_DATA_DIRS (via environment.d) so GNOME finds desktop entries
  # and icons of nix-installed GUI apps (e.g. zen-beta).
  targets.genericLinux.enable = true;

  # home-manager owns ~/.bashrc and ~/.profile (first switch on a machine
  # needs `switch -b backup` to move the pre-existing real files aside).
  # Machine-specific lines and secrets go in ~/.bashrc.local — never here.
  programs.bash = {
    enable = true;
    # Match Ubuntu's stock history behavior.
    historyControl = [ "ignoreboth" ];
    historySize = 1000;
    historyFileSize = 2000;
    shellAliases = {
      ccode = "claude";
      ls = "ls --color=auto";
      grep = "grep --color=auto";
      ll = "ls -alF";
      la = "ls -A";
      l = "ls -CF";
    };
    initExtra = ''
      # bash-completion (Ubuntu system package)
      if ! shopt -oq posix; then
        if [ -f /usr/share/bash-completion/bash_completion ]; then
          . /usr/share/bash-completion/bash_completion
        elif [ -f /etc/bash_completion ]; then
          . /etc/bash_completion
        fi
      fi

      export PATH="$HOME/.local/bin:$PATH"

      # Rust toolchain (rustup is installed by install.sh)
      [ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

      # Nix daemon env for non-login shells
      [ -e /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh ] \
        && . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

      # Machine-specific config and secrets (not in dotfiles repo)
      [ -f "$HOME/.bashrc.local" ] && . "$HOME/.bashrc.local"
    '';
  };

  # Shell integrations — these enable the packages AND wire up their
  # bash init hooks declaratively.
  programs.starship.enable = true;
  programs.zoxide.enable = true;

  programs.home-manager.enable = true;
}
